/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Numeric = ColumnType<string, number | string, number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface AccountingPeriods {
  id: Generated<string>;
  locked_at: Timestamp | null;
  locked_by: string | null;
  period_end: string;
  period_start: string;
  soft_locked_at: Timestamp | null;
  soft_locked_by: string | null;
  status: Generated<string>;
  unlock_reason: string | null;
  unlocked_at: Timestamp | null;
  unlocked_by: string | null;
}

export interface Accounts {
  branch_id: string | null;
  code: string;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  employee_id: string | null;
  id: Generated<string>;
  is_active: Generated<boolean>;
  is_postable: Generated<boolean>;
  is_system: Generated<boolean>;
  name: string;
  normal_balance: string;
  parent_id: string | null;
  subtype: string | null;
  type: string;
}

export interface AdvanceApplications {
  amount: Numeric;
  applied_on: string;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  journal_entry_id: string | null;
  loan_id: string;
  reversal_journal_entry_id: string | null;
  reversed_at: Timestamp | null;
  status: Generated<string>;
}

export interface AssetDocuments {
  asset_id: string;
  created_at: Generated<Timestamp>;
  created_by: string;
  doc_type: string;
  expiry_date: string | null;
  file_id: string;
  id: Generated<string>;
}

export interface AssetEvents {
  actor_id: string | null;
  asset_id: string;
  at: Generated<Timestamp>;
  from_status: string | null;
  id: Generated<Int8>;
  reason: string | null;
  to_status: string;
}

export interface Assets {
  asset_no: string;
  asset_value: Numeric | null;
  attributes: Generated<Json>;
  branch_id: string;
  category: string;
  chassis_no: string | null;
  colour: string | null;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  customer_id: string;
  dealer_name: string | null;
  description: string | null;
  engine_no: string | null;
  fitness_expiry: string | null;
  hypothecation_date: string | null;
  hypothecation_marked: Generated<boolean>;
  id: Generated<string>;
  insurance_expiry: string | null;
  insurance_policy_no: string | null;
  insurer: string | null;
  invoice_no: string | null;
  loan_id: string;
  make: string | null;
  manufacture_year: number | null;
  model: string | null;
  permit_expiry: string | null;
  permit_no: string | null;
  purchase_date: string | null;
  purchase_price: Numeric | null;
  registration_no: string | null;
  serial_no: string | null;
  status: Generated<string>;
  tax_valid_till: string | null;
  updated_at: Generated<Timestamp>;
  updated_by: string | null;
  variant: string | null;
  vehicle_type: string | null;
  version: Generated<number>;
}

export interface AuditLogs {
  action: string;
  at: Generated<Timestamp>;
  branch_id: string | null;
  entity_id: string | null;
  entity_type: string | null;
  hash: Buffer;
  id: Generated<Int8>;
  ip: string | null;
  new_values: Json | null;
  old_values: Json | null;
  prev_hash: Buffer | null;
  reason: string | null;
  request_id: string | null;
  role_codes: Generated<string[]>;
  session_id: string | null;
  user_agent: string | null;
  user_id: string | null;
}

export interface BankAccounts {
  account_id: string;
  account_no_enc: Buffer | null;
  account_no_last4: string | null;
  bank_name: string;
  branch_name: string | null;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  id: Generated<string>;
  ifsc: string | null;
  kind: string;
  upi_vpa: string | null;
}

export interface BankStatementImports {
  account_id: string;
  file_name: string;
  file_sha256: string;
  id: Generated<string>;
  imported_at: Generated<Timestamp>;
  imported_by: string;
  invalid_rows: Generated<Json>;
  mapping: Json;
  period_from: string | null;
  period_to: string | null;
  rows_duplicate: number;
  rows_invalid: number;
  rows_new: number;
  rows_total: number;
}

export interface BankStatementLines {
  account_id: string;
  balance: Numeric | null;
  created_at: Generated<Timestamp>;
  credit: Generated<Numeric>;
  debit: Generated<Numeric>;
  description: string;
  handled_at: Timestamp | null;
  handled_by: string | null;
  id: Generated<string>;
  ignore_reason: string | null;
  import_id: string;
  match_status: Generated<string>;
  reference: string | null;
  row_hash: string;
  seq: Generated<Int8>;
  txn_date: string;
  utr: string | null;
}

export interface Branches {
  address: string | null;
  code: string;
  company_id: string;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  id: Generated<string>;
  is_active: Generated<boolean>;
  name: string;
  phone: string | null;
  updated_at: Generated<Timestamp>;
  updated_by: string | null;
  version: Generated<number>;
}

export interface BusinessDays {
  branch_id: string;
  business_date: string;
  closed_at: Timestamp | null;
  closed_by: string | null;
  id: Generated<string>;
  reopen_reason: string | null;
  reopen_requested_at: Timestamp | null;
  reopen_requested_by: string | null;
  reopened_at: Timestamp | null;
  reopened_by: string | null;
  status: Generated<string>;
  summary: Json | null;
}

export interface CashDeposits {
  amount: Numeric;
  branch_id: string;
  deposit_no: string;
  deposited_on: string;
  employee_id: string | null;
  file_id: string | null;
  from_account_id: string;
  id: Generated<string>;
  journal_entry_id: string | null;
  notes: string | null;
  reconciled_at: Timestamp | null;
  reconciliation_status: Generated<string>;
  recorded_at: Generated<Timestamp>;
  recorded_by: string;
  reversal_journal_entry_id: string | null;
  reverse_reason: string | null;
  reversed_at: Timestamp | null;
  reversed_by: string | null;
  slip_no: string | null;
  status: Generated<string>;
  to_account_id: string;
}

export interface CollectionAssignments {
  assigned_by: string;
  employee_id: string;
  from_at: Generated<Timestamp>;
  id: Generated<string>;
  loan_id: string;
  reason: string | null;
  to_at: Timestamp | null;
}

export interface CollectionVisits {
  created_by: string;
  customer_id: string;
  employee_id: string | null;
  id: Generated<string>;
  lat: Numeric | null;
  lng: Numeric | null;
  loan_id: string;
  notes: string | null;
  outcome: string;
  payment_id: string | null;
  promise_id: string | null;
  visited_at: Generated<Timestamp>;
}

export interface Companies {
  address: string | null;
  created_at: Generated<Timestamp>;
  currency: Generated<string>;
  date_format: Generated<string>;
  email: string | null;
  fy_start_month: Generated<number>;
  gstin: string | null;
  id: Generated<string>;
  legal_name: string;
  logo_file_id: string | null;
  phone: string | null;
  receipt_footer: string | null;
  timezone: Generated<string>;
  trade_name: string | null;
  updated_at: Generated<Timestamp>;
  updated_by: string | null;
}

export interface CustomerDocuments {
  category: string;
  created_at: Generated<Timestamp>;
  created_by: string;
  customer_id: string;
  file_id: string;
  id: Generated<string>;
  notes: string | null;
}

export interface CustomerEvents {
  actor_id: string | null;
  at: Generated<Timestamp>;
  customer_id: string;
  event_type: string;
  id: Generated<Int8>;
  loan_id: string | null;
  ref_id: string | null;
  ref_type: string | null;
  summary: string;
}

export interface CustomerKycDocuments {
  created_at: Generated<Timestamp>;
  created_by: string | null;
  customer_id: string;
  doc_type: string;
  id: Generated<string>;
  key_version: number | null;
  number_bidx: Buffer | null;
  number_enc: Buffer | null;
  number_last4: string;
  updated_at: Generated<Timestamp>;
  verification_method: string | null;
  verified_at: Timestamp | null;
  verified_by: string | null;
}

export interface CustomerReferences {
  address: string | null;
  customer_id: string;
  id: Generated<string>;
  mobile: string;
  name: string;
  relationship: string;
  sort_order: Generated<number>;
}

export interface Customers {
  address_line1: string | null;
  address_line2: string | null;
  alt_mobile: string | null;
  branch_id: string;
  business_type: string | null;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  customer_no: string;
  district: string | null;
  dob: string | null;
  email: string | null;
  employer_business_name: string | null;
  full_name: string;
  gender: string | null;
  id: Generated<string>;
  kyc_status: Generated<string>;
  mandal: string | null;
  mobile: string;
  monthly_income: Numeric | null;
  occupation: string | null;
  pincode: string | null;
  relation_name: string | null;
  relation_type: string | null;
  risk_category: Generated<string>;
  state: string | null;
  status: Generated<string>;
  updated_at: Generated<Timestamp>;
  updated_by: string | null;
  version: Generated<number>;
  village_town: string | null;
  whatsapp_opt_in: Generated<boolean>;
  whatsapp_opt_in_at: Timestamp | null;
  work_address: string | null;
}

export interface Employees {
  branch_id: string;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  designation: string | null;
  employee_code: string;
  full_name: string;
  id: Generated<string>;
  is_collector: Generated<boolean>;
  joined_on: string | null;
  mobile: string | null;
  status: Generated<string>;
  updated_at: Generated<Timestamp>;
  updated_by: string | null;
  user_id: string | null;
  version: Generated<number>;
}

export interface EmployeeSettlements {
  approved_at: Timestamp | null;
  approved_by: string | null;
  branch_id: string;
  business_date: string;
  counted_at: Timestamp | null;
  counted_by: string | null;
  counted_cash: Numeric | null;
  declaration_note: string | null;
  declared_at: Timestamp | null;
  declared_by: string | null;
  declared_cash: Numeric | null;
  difference: Numeric | null;
  employee_id: string;
  employee_user_id: string | null;
  expected_cash: Numeric | null;
  id: Generated<string>;
  snapshot: Json | null;
  status: Generated<string>;
  version: Generated<number>;
}

export interface ExpenseCategories {
  account_id: string;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  is_active: Generated<boolean>;
  name: string;
  requires_bill: Generated<boolean>;
}

export interface Expenses {
  amount: Numeric;
  approved_at: Timestamp | null;
  approved_by: string | null;
  bill_no: string | null;
  branch_id: string;
  category_id: string;
  description: string;
  employee_id: string | null;
  expense_date: string;
  expense_no: string;
  file_id: string | null;
  id: Generated<string>;
  journal_entry_id: string | null;
  paid_from: string;
  paid_from_account_id: string;
  posted_at: Timestamp | null;
  posted_by: string | null;
  reject_reason: string | null;
  rejected_at: Timestamp | null;
  rejected_by: string | null;
  reversal_journal_entry_id: string | null;
  reverse_reason: string | null;
  reversed_at: Timestamp | null;
  reversed_by: string | null;
  status: Generated<string>;
  submitted_at: Generated<Timestamp>;
  submitted_by: string;
  vendor: string | null;
}

export interface Files {
  classification: string;
  id: Generated<string>;
  mime_type: string;
  original_name: string;
  scan_status: Generated<string>;
  sha256: Buffer;
  size_bytes: number;
  storage_key: string;
  uploaded_at: Generated<Timestamp>;
  uploaded_by: string;
}

export interface IdempotencyKeys {
  created_at: Generated<Timestamp>;
  expires_at: Generated<Timestamp>;
  key: string;
  request_hash: Buffer;
  response_body: Json;
  response_status: number;
  route: string;
  user_id: string;
}

export interface JobRuns {
  business_date: string;
  details: Json | null;
  finished_at: Timestamp | null;
  job: string;
  started_at: Generated<Timestamp>;
  status: string;
}

export interface JournalEntries {
  approved_by: string | null;
  branch_id: string | null;
  created_by: string | null;
  entry_no: string;
  entry_type: string;
  id: Generated<string>;
  narration: string;
  posted_at: Generated<Timestamp>;
  reverses_entry_id: string | null;
  source_id: string | null;
  source_type: string | null;
  value_date: string;
}

export interface JournalLines {
  account_id: string;
  branch_id: string | null;
  credit: Generated<Numeric>;
  customer_id: string | null;
  debit: Generated<Numeric>;
  employee_id: string | null;
  entry_id: string;
  id: Generated<string>;
  line_no: number;
  loan_id: string | null;
  memo: string | null;
}

export interface LoanCharges {
  amount: Numeric;
  assessed_on: string;
  charge_type: string;
  code: string;
  collection_mode: string | null;
  created_at: Generated<Timestamp>;
  description: string;
  gst_amount: Generated<Numeric>;
  id: Generated<string>;
  installment_id: string | null;
  journal_entry_id: string | null;
  loan_id: string;
  status: Generated<string>;
}

export interface LoanClosures {
  advance_remaining: Generated<Numeric>;
  checklist: Generated<Json>;
  closed_on: string;
  closing_payment_id: string | null;
  created_at: Generated<Timestamp>;
  fees_paid: Numeric;
  id: Generated<string>;
  interest_paid: Numeric;
  loan_id: string;
  penalty_paid: Numeric;
  principal_paid: Numeric;
  status: Generated<string>;
  total_paid: Numeric;
  void_reason: string | null;
  voided_at: Timestamp | null;
}

export interface LoanInstallments {
  closing_principal: Numeric;
  days_overdue: Generated<number>;
  due_date: string;
  fees_due: Generated<Numeric>;
  fees_paid: Generated<Numeric>;
  id: Generated<string>;
  installment_no: number;
  interest_accrued_at: Timestamp | null;
  interest_due: Numeric;
  interest_paid: Generated<Numeric>;
  loan_id: string;
  opening_principal: Numeric;
  paid_on: string | null;
  penalty_due: Generated<Numeric>;
  penalty_paid: Generated<Numeric>;
  principal_due: Numeric;
  principal_paid: Generated<Numeric>;
  schedule_version: Generated<number>;
  status: Generated<string>;
  total_due: Generated<Numeric | null>;
  total_paid: Generated<Numeric | null>;
  waived_amount: Generated<Numeric>;
}

export interface LoanProducts {
  allocation_rule: Json;
  allowed_frequencies: string[];
  amount_max: Numeric;
  amount_min: Numeric;
  approval_limit: Numeric | null;
  category: string;
  code: string;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  description: string | null;
  fee_rules: Generated<Json>;
  id: Generated<string>;
  interest_method: string;
  is_latest: Generated<boolean>;
  max_ltv_pct: Numeric | null;
  name: string;
  penalty_rule: Json;
  rate_default: Numeric;
  rate_max: Numeric;
  rate_min: Numeric;
  rounding_unit: Generated<string>;
  skip_sundays: Generated<boolean>;
  status: Generated<string>;
  tenure_max: number;
  tenure_min: number;
  version: Generated<number>;
}

export interface Loans {
  advance_balance: Generated<Numeric>;
  allocation_rule: Json;
  annual_rate: Numeric;
  approved_at: Timestamp | null;
  approved_by: string | null;
  apr: Numeric;
  asset_value: Numeric | null;
  assigned_collector_id: string | null;
  balance_payable: Generated<Numeric>;
  branch_id: string;
  calc_snapshot: Json;
  cancel_reason: string | null;
  cancelled_at: Timestamp | null;
  cancelled_by: string | null;
  category: string;
  closed_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  created_by: string;
  custom_interval_days: number | null;
  customer_id: string;
  decision_note: string | null;
  disbursed_at: Timestamp | null;
  disbursed_on: string | null;
  disbursement_account_id: string | null;
  disbursement_date: string;
  disbursement_journal_id: string | null;
  disbursement_mode: string | null;
  disbursement_reference: string | null;
  down_payment: Generated<Numeric>;
  dpd: Generated<number>;
  engine_version: string;
  fees: Generated<Json>;
  fees_deducted: Numeric;
  fees_in_installments: Numeric;
  fees_outstanding: Generated<Numeric>;
  first_due_date: string;
  frequency: string;
  id: Generated<string>;
  installment_amount: Numeric;
  interest_method: string;
  interest_outstanding: Generated<Numeric>;
  last_payment_at: Timestamp | null;
  loan_no: string;
  maturity_date: string;
  net_disbursement: Numeric;
  next_due_amount: Numeric | null;
  next_due_date: string | null;
  num_installments: number;
  overdue_amount: Generated<Numeric>;
  penalty_outstanding: Generated<Numeric>;
  penalty_rule: Json;
  principal: Numeric;
  principal_outstanding: Generated<Numeric>;
  product_id: string;
  rejected_at: Timestamp | null;
  rejected_by: string | null;
  rounding_unit: string;
  skip_sundays: Generated<boolean>;
  status: Generated<string>;
  submitted_at: Timestamp | null;
  submitted_by: string | null;
  total_collected: Generated<Numeric>;
  total_fees: Numeric;
  total_gst: Numeric;
  total_interest: Numeric;
  total_payable: Numeric;
  updated_at: Generated<Timestamp>;
  version: Generated<number>;
}

export interface LoginEvents {
  at: Generated<Timestamp>;
  id: Generated<Int8>;
  identifier: string;
  ip: string | null;
  reason: string;
  success: boolean;
  user_agent: string | null;
  user_id: string | null;
}

export interface ManualJournals {
  branch_id: string | null;
  created_at: Generated<Timestamp>;
  created_by: string;
  decided_at: Timestamp | null;
  decided_by: string | null;
  decision_note: string | null;
  id: Generated<string>;
  journal_entry_id: string | null;
  lines: Json;
  narration: string;
  status: Generated<string>;
  total: Numeric;
  value_date: string;
}

export interface MessageEvents {
  at: Generated<Timestamp>;
  detail: Generated<Json>;
  id: Generated<Int8>;
  message_id: string | null;
  source: string;
  status: string | null;
}

export interface Messages {
  attempts: Generated<number>;
  available_at: Generated<Timestamp>;
  body: string;
  channel: string;
  created_by: string | null;
  customer_id: string | null;
  dedupe_key: string | null;
  delivered_at: Timestamp | null;
  error_text: string | null;
  event_code: string;
  failed_at: Timestamp | null;
  id: Generated<string>;
  installment_id: string | null;
  loan_id: string | null;
  params: Generated<Json>;
  payment_id: string | null;
  provider: string | null;
  provider_message_id: string | null;
  queued_at: Generated<Timestamp>;
  read_at: Timestamp | null;
  sent_at: Timestamp | null;
  skip_reason: string | null;
  status: Generated<string>;
  template_id: string | null;
  to_number: string;
  triggered_by: Generated<string>;
}

export interface MessageTemplates {
  body: string;
  channel: string;
  dlt_template_id: string | null;
  event_code: string;
  id: Generated<string>;
  is_active: Generated<boolean>;
  language: Generated<string>;
  updated_at: Generated<Timestamp>;
  updated_by: string | null;
  variables: string[];
  wa_language: Generated<string>;
  wa_template_name: string | null;
}

export interface MfaRecoveryCodes {
  code_hash: Buffer;
  id: Generated<string>;
  used_at: Timestamp | null;
  user_id: string;
}

export interface NumberingFormats {
  format: string;
  seq_type: string;
  updated_at: Generated<Timestamp>;
  updated_by: string | null;
}

export interface NumberingSequences {
  fiscal_year: number;
  next_value: Generated<Int8>;
  scope_key: Generated<string>;
  seq_type: string;
}

export interface Outbox {
  attempts: Generated<number>;
  available_at: Generated<Timestamp>;
  created_at: Generated<Timestamp>;
  id: Generated<Int8>;
  last_error: string | null;
  payload: Json;
  processed_at: Timestamp | null;
  topic: string;
}

export interface PasswordResetTokens {
  created_at: Generated<Timestamp>;
  created_by: string | null;
  expires_at: Timestamp;
  id: Generated<string>;
  token_hash: Buffer;
  used_at: Timestamp | null;
  user_id: string;
}

export interface PaymentAllocations {
  advance_application_id: string | null;
  amount: Numeric;
  component: string;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  installment_id: string | null;
  installment_no: number | null;
  loan_id: string;
  payment_id: string | null;
  rule_snapshot: Json;
  seq: number;
}

export interface PaymentReversals {
  decided_at: Timestamp | null;
  decided_by: string | null;
  decision_note: string | null;
  id: Generated<string>;
  payment_id: string;
  reason_code: string;
  reason_text: string;
  requested_at: Generated<Timestamp>;
  requested_by: string;
  reversal_journal_entry_id: string | null;
  status: Generated<string>;
}

export interface Payments {
  advance_amount: Generated<Numeric>;
  amount: Numeric;
  branch_id: string;
  business_date: string;
  cheque_bank: string | null;
  cheque_bounced_on: string | null;
  cheque_cleared_on: string | null;
  cheque_date: string | null;
  cheque_deposit_account_id: string | null;
  cheque_deposit_journal_id: string | null;
  cheque_deposited_on: string | null;
  cheque_status: string | null;
  collected_by: string | null;
  created_at: Generated<Timestamp>;
  customer_id: string;
  debit_account_id: string;
  id: Generated<string>;
  journal_entry_id: string | null;
  lat: Numeric | null;
  lng: Numeric | null;
  loan_id: string;
  location_text: string | null;
  method: string;
  notes: string | null;
  payment_no: string;
  received_at: Generated<Timestamp>;
  reconciled_at: Timestamp | null;
  reconciliation_status: Generated<string>;
  recorded_by: string;
  reference_no: string | null;
  settlement_id: string | null;
  status: Generated<string>;
  value_date: string;
}

export interface Permissions {
  code: string;
  description: string;
}

export interface PromisesToPay {
  created_at: Generated<Timestamp>;
  created_by: string;
  customer_id: string;
  employee_id: string | null;
  id: Generated<string>;
  loan_id: string;
  paid_amount: Generated<Numeric>;
  promised_amount: Numeric;
  promised_date: string;
  resolved_at: Timestamp | null;
  status: Generated<string>;
}

export interface Receipts {
  cancelled_at: Timestamp | null;
  cancelled_by_reversal_id: string | null;
  id: Generated<string>;
  issued_at: Generated<Timestamp>;
  payment_id: string;
  receipt_no: string;
  snapshot: Json;
  status: Generated<string>;
  verify_token: string;
}

export interface ReconciliationMatches {
  amount: Numeric;
  confidence: Numeric;
  confirmed_at: Timestamp | null;
  confirmed_by: string | null;
  id: Generated<string>;
  journal_entry_id: string | null;
  method: string;
  statement_line_id: string;
  status: Generated<string>;
  suggested_at: Generated<Timestamp>;
  target_id: string;
  target_type: string;
  undo_journal_entry_id: string | null;
  undo_reason: string | null;
  undone_at: Timestamp | null;
  undone_by: string | null;
}

export interface ReminderRules {
  channel: string;
  event_code: string;
  id: Generated<string>;
  is_active: Generated<boolean>;
  min_amount: Generated<Numeric>;
  offset_days: number;
  updated_at: Generated<Timestamp>;
  updated_by: string | null;
}

export interface RolePermissions {
  permission_code: string;
  role_id: string;
}

export interface Roles {
  code: string;
  id: Generated<string>;
  is_system: Generated<boolean>;
  mfa_required: Generated<boolean>;
  name: string;
  scope: string;
}

export interface Sessions {
  created_at: Generated<Timestamp>;
  csrf_hash: Buffer;
  expires_at: Timestamp;
  id: Generated<string>;
  ip: string | null;
  last_seen_at: Generated<Timestamp>;
  mfa_pending: Generated<boolean>;
  reauth_at: Timestamp | null;
  revoke_reason: string | null;
  revoked_at: Timestamp | null;
  token_hash: Buffer;
  user_agent: string | null;
  user_id: string;
}

export interface SettlementDifferences {
  amount: Numeric;
  decided_at: Timestamp | null;
  decided_by: string | null;
  decision_note: string | null;
  direction: string;
  id: Generated<string>;
  journal_entry_id: string | null;
  notes: string;
  reason_code: string;
  recorded_at: Generated<Timestamp>;
  recorded_by: string;
  resolution: string;
  settlement_id: string;
  status: Generated<string>;
}

export interface SystemSettings {
  key: string;
  updated_at: Generated<Timestamp>;
  updated_by: string | null;
  value: Json;
}

export interface UserBranches {
  branch_id: string;
  user_id: string;
}

export interface UserPermissionOverrides {
  effect: string;
  permission_code: string;
  user_id: string;
}

export interface UserRoles {
  role_id: string;
  user_id: string;
}

export interface Users {
  created_at: Generated<Timestamp>;
  created_by: string | null;
  email: string | null;
  failed_login_count: Generated<number>;
  full_name: string;
  id: Generated<string>;
  last_login_at: Timestamp | null;
  locked_until: Timestamp | null;
  lockout_level: Generated<number>;
  mfa_enabled: Generated<boolean>;
  mobile: string | null;
  must_change_password: Generated<boolean>;
  password_changed_at: Generated<Timestamp>;
  password_hash: string;
  status: Generated<string>;
  totp_last_step: Int8 | null;
  totp_pending_enc: Buffer | null;
  totp_secret_enc: Buffer | null;
  updated_at: Generated<Timestamp>;
  updated_by: string | null;
  username: string;
  version: Generated<number>;
}

export interface DB {
  accounting_periods: AccountingPeriods;
  accounts: Accounts;
  advance_applications: AdvanceApplications;
  asset_documents: AssetDocuments;
  asset_events: AssetEvents;
  assets: Assets;
  audit_logs: AuditLogs;
  bank_accounts: BankAccounts;
  bank_statement_imports: BankStatementImports;
  bank_statement_lines: BankStatementLines;
  branches: Branches;
  business_days: BusinessDays;
  cash_deposits: CashDeposits;
  collection_assignments: CollectionAssignments;
  collection_visits: CollectionVisits;
  companies: Companies;
  customer_documents: CustomerDocuments;
  customer_events: CustomerEvents;
  customer_kyc_documents: CustomerKycDocuments;
  customer_references: CustomerReferences;
  customers: Customers;
  employee_settlements: EmployeeSettlements;
  employees: Employees;
  expense_categories: ExpenseCategories;
  expenses: Expenses;
  files: Files;
  idempotency_keys: IdempotencyKeys;
  job_runs: JobRuns;
  journal_entries: JournalEntries;
  journal_lines: JournalLines;
  loan_charges: LoanCharges;
  loan_closures: LoanClosures;
  loan_installments: LoanInstallments;
  loan_products: LoanProducts;
  loans: Loans;
  login_events: LoginEvents;
  manual_journals: ManualJournals;
  message_events: MessageEvents;
  message_templates: MessageTemplates;
  messages: Messages;
  mfa_recovery_codes: MfaRecoveryCodes;
  numbering_formats: NumberingFormats;
  numbering_sequences: NumberingSequences;
  outbox: Outbox;
  password_reset_tokens: PasswordResetTokens;
  payment_allocations: PaymentAllocations;
  payment_reversals: PaymentReversals;
  payments: Payments;
  permissions: Permissions;
  promises_to_pay: PromisesToPay;
  receipts: Receipts;
  reconciliation_matches: ReconciliationMatches;
  reminder_rules: ReminderRules;
  role_permissions: RolePermissions;
  roles: Roles;
  sessions: Sessions;
  settlement_differences: SettlementDifferences;
  system_settings: SystemSettings;
  user_branches: UserBranches;
  user_permission_overrides: UserPermissionOverrides;
  user_roles: UserRoles;
  users: Users;
}
