/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Numeric = ColumnType<string, number | string, number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface AuditLogs {
  action: string;
  at: Generated<Timestamp>;
  branch_id: string | null;
  entity_id: string | null;
  entity_type: string | null;
  hash: Buffer;
  id: Generated<Int8>;
  ip: string | null;
  new_values: Json | null;
  old_values: Json | null;
  prev_hash: Buffer | null;
  reason: string | null;
  request_id: string | null;
  role_codes: Generated<string[]>;
  session_id: string | null;
  user_agent: string | null;
  user_id: string | null;
}

export interface Branches {
  address: string | null;
  code: string;
  company_id: string;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  id: Generated<string>;
  is_active: Generated<boolean>;
  name: string;
  phone: string | null;
  updated_at: Generated<Timestamp>;
  updated_by: string | null;
  version: Generated<number>;
}

export interface Companies {
  address: string | null;
  created_at: Generated<Timestamp>;
  currency: Generated<string>;
  date_format: Generated<string>;
  email: string | null;
  fy_start_month: Generated<number>;
  gstin: string | null;
  id: Generated<string>;
  legal_name: string;
  logo_file_id: string | null;
  phone: string | null;
  receipt_footer: string | null;
  timezone: Generated<string>;
  trade_name: string | null;
  updated_at: Generated<Timestamp>;
  updated_by: string | null;
}

export interface CustomerDocuments {
  category: string;
  created_at: Generated<Timestamp>;
  created_by: string;
  customer_id: string;
  file_id: string;
  id: Generated<string>;
  notes: string | null;
}

export interface CustomerEvents {
  actor_id: string | null;
  at: Generated<Timestamp>;
  customer_id: string;
  event_type: string;
  id: Generated<Int8>;
  ref_id: string | null;
  ref_type: string | null;
  summary: string;
}

export interface CustomerKycDocuments {
  created_at: Generated<Timestamp>;
  created_by: string | null;
  customer_id: string;
  doc_type: string;
  id: Generated<string>;
  key_version: number | null;
  number_bidx: Buffer | null;
  number_enc: Buffer | null;
  number_last4: string;
  updated_at: Generated<Timestamp>;
  verification_method: string | null;
  verified_at: Timestamp | null;
  verified_by: string | null;
}

export interface CustomerReferences {
  address: string | null;
  customer_id: string;
  id: Generated<string>;
  mobile: string;
  name: string;
  relationship: string;
  sort_order: Generated<number>;
}

export interface Customers {
  address_line1: string | null;
  address_line2: string | null;
  alt_mobile: string | null;
  branch_id: string;
  business_type: string | null;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  customer_no: string;
  district: string | null;
  dob: string | null;
  email: string | null;
  employer_business_name: string | null;
  full_name: string;
  gender: string | null;
  id: Generated<string>;
  kyc_status: Generated<string>;
  mandal: string | null;
  mobile: string;
  monthly_income: Numeric | null;
  occupation: string | null;
  pincode: string | null;
  relation_name: string | null;
  relation_type: string | null;
  risk_category: Generated<string>;
  state: string | null;
  status: Generated<string>;
  updated_at: Generated<Timestamp>;
  updated_by: string | null;
  version: Generated<number>;
  village_town: string | null;
  whatsapp_opt_in: Generated<boolean>;
  whatsapp_opt_in_at: Timestamp | null;
  work_address: string | null;
}

export interface Employees {
  branch_id: string;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  designation: string | null;
  employee_code: string;
  full_name: string;
  id: Generated<string>;
  is_collector: Generated<boolean>;
  joined_on: string | null;
  mobile: string | null;
  status: Generated<string>;
  updated_at: Generated<Timestamp>;
  updated_by: string | null;
  user_id: string | null;
  version: Generated<number>;
}

export interface Files {
  classification: string;
  id: Generated<string>;
  mime_type: string;
  original_name: string;
  scan_status: Generated<string>;
  sha256: Buffer;
  size_bytes: number;
  storage_key: string;
  uploaded_at: Generated<Timestamp>;
  uploaded_by: string;
}

export interface IdempotencyKeys {
  created_at: Generated<Timestamp>;
  expires_at: Generated<Timestamp>;
  key: string;
  request_hash: Buffer;
  response_body: Json;
  response_status: number;
  route: string;
  user_id: string;
}

export interface LoginEvents {
  at: Generated<Timestamp>;
  id: Generated<Int8>;
  identifier: string;
  ip: string | null;
  reason: string;
  success: boolean;
  user_agent: string | null;
  user_id: string | null;
}

export interface MfaRecoveryCodes {
  code_hash: Buffer;
  id: Generated<string>;
  used_at: Timestamp | null;
  user_id: string;
}

export interface NumberingFormats {
  format: string;
  seq_type: string;
  updated_at: Generated<Timestamp>;
  updated_by: string | null;
}

export interface NumberingSequences {
  fiscal_year: number;
  next_value: Generated<Int8>;
  scope_key: Generated<string>;
  seq_type: string;
}

export interface Outbox {
  attempts: Generated<number>;
  available_at: Generated<Timestamp>;
  created_at: Generated<Timestamp>;
  id: Generated<Int8>;
  last_error: string | null;
  payload: Json;
  processed_at: Timestamp | null;
  topic: string;
}

export interface PasswordResetTokens {
  created_at: Generated<Timestamp>;
  created_by: string | null;
  expires_at: Timestamp;
  id: Generated<string>;
  token_hash: Buffer;
  used_at: Timestamp | null;
  user_id: string;
}

export interface Permissions {
  code: string;
  description: string;
}

export interface RolePermissions {
  permission_code: string;
  role_id: string;
}

export interface Roles {
  code: string;
  id: Generated<string>;
  is_system: Generated<boolean>;
  mfa_required: Generated<boolean>;
  name: string;
  scope: string;
}

export interface Sessions {
  created_at: Generated<Timestamp>;
  csrf_hash: Buffer;
  expires_at: Timestamp;
  id: Generated<string>;
  ip: string | null;
  last_seen_at: Generated<Timestamp>;
  mfa_pending: Generated<boolean>;
  reauth_at: Timestamp | null;
  revoke_reason: string | null;
  revoked_at: Timestamp | null;
  token_hash: Buffer;
  user_agent: string | null;
  user_id: string;
}

export interface SystemSettings {
  key: string;
  updated_at: Generated<Timestamp>;
  updated_by: string | null;
  value: Json;
}

export interface UserBranches {
  branch_id: string;
  user_id: string;
}

export interface UserPermissionOverrides {
  effect: string;
  permission_code: string;
  user_id: string;
}

export interface UserRoles {
  role_id: string;
  user_id: string;
}

export interface Users {
  created_at: Generated<Timestamp>;
  created_by: string | null;
  email: string | null;
  failed_login_count: Generated<number>;
  full_name: string;
  id: Generated<string>;
  last_login_at: Timestamp | null;
  locked_until: Timestamp | null;
  lockout_level: Generated<number>;
  mfa_enabled: Generated<boolean>;
  mobile: string | null;
  must_change_password: Generated<boolean>;
  password_changed_at: Generated<Timestamp>;
  password_hash: string;
  status: Generated<string>;
  totp_last_step: Int8 | null;
  totp_pending_enc: Buffer | null;
  totp_secret_enc: Buffer | null;
  updated_at: Generated<Timestamp>;
  updated_by: string | null;
  username: string;
  version: Generated<number>;
}

export interface DB {
  audit_logs: AuditLogs;
  branches: Branches;
  companies: Companies;
  customer_documents: CustomerDocuments;
  customer_events: CustomerEvents;
  customer_kyc_documents: CustomerKycDocuments;
  customer_references: CustomerReferences;
  customers: Customers;
  employees: Employees;
  files: Files;
  idempotency_keys: IdempotencyKeys;
  login_events: LoginEvents;
  mfa_recovery_codes: MfaRecoveryCodes;
  numbering_formats: NumberingFormats;
  numbering_sequences: NumberingSequences;
  outbox: Outbox;
  password_reset_tokens: PasswordResetTokens;
  permissions: Permissions;
  role_permissions: RolePermissions;
  roles: Roles;
  sessions: Sessions;
  system_settings: SystemSettings;
  user_branches: UserBranches;
  user_permission_overrides: UserPermissionOverrides;
  user_roles: UserRoles;
  users: Users;
}
