import { GetObjectCommand, PutObjectCommand, S3Client } from '@aws-sdk/client-s3';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, join, resolve } from 'node:path';

/** Where uploaded documents live. Keys are generated by the app (never from user input). */
export interface BlobStore {
  /** Writes once: an existing key is never overwritten. */
  put(key: string, data: Buffer, contentType: string): Promise<void>;
  get(key: string): Promise<Buffer>;
}

/** Private local directory (development, and the single-server pilot with a backed-up volume). */
export class LocalStore implements BlobStore {
  private readonly root: string;
  constructor(dir: string) {
    this.root = resolve(dir);
  }
  private path(key: string) {
    const p = resolve(join(this.root, key));
    if (!p.startsWith(this.root + '/')) throw new Error('Invalid storage key');
    return p;
  }
  async put(key: string, data: Buffer, _contentType?: string) {
    const p = this.path(key);
    await mkdir(dirname(p), { recursive: true, mode: 0o700 });
    await writeFile(p, data, { mode: 0o600, flag: 'wx' });
  }
  async get(key: string) {
    return readFile(this.path(key));
  }
}

/**
 * Private S3 bucket (production, doc 13): server-side encryption with the app's KMS key, write-once
 * (If-None-Match), credentials from the ECS task role — never from configuration. Downloads stream
 * through the API, which checks permissions and the malware-scan status first; there are no public
 * or presigned links.
 */
export class S3Store implements BlobStore {
  private readonly s3: S3Client;
  constructor(private readonly opts: { bucket: string; region: string; prefix: string; kmsKeyId: string | null; endpoint?: string | null }) {
    this.s3 = new S3Client({ region: opts.region, ...(opts.endpoint ? { endpoint: opts.endpoint, forcePathStyle: true } : {}) });
  }
  async put(key: string, data: Buffer, contentType: string) {
    await this.s3.send(
      new PutObjectCommand({
        Bucket: this.opts.bucket,
        Key: this.opts.prefix + key,
        Body: data,
        ContentType: contentType,
        IfNoneMatch: '*',
        ServerSideEncryption: 'aws:kms',
        ...(this.opts.kmsKeyId ? { SSEKMSKeyId: this.opts.kmsKeyId } : {}),
      }),
    );
  }
  async get(key: string) {
    const r = await this.s3.send(new GetObjectCommand({ Bucket: this.opts.bucket, Key: this.opts.prefix + key }));
    return Buffer.from(await r.Body!.transformToByteArray());
  }
}
